name: CI

on:
  push:

  schedule:
  - cron: "14 * * * 0,1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master


    - run: git config --global user.email "robot+hal@bessarabov.ru"
    - run: git config --global user.name "HAL 9000"
    - run: git remote rm origin
    - name: Setup git repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git remote add origin https://bessarabov:$GITHUB_TOKEN@github.com/bessarabov/radio-t-data


    - name: Docker pull base image
      run: docker pull golang:1.13.8-alpine3.11

    - name: Build docker image
      run: cd code; docker build . --tag code:${{ github.sha }}

    - name: Run code
      run: docker run --rm --volume `pwd`/data/:/data/ code:${{ github.sha }}


    - run: git add data
    - run: git commit --allow-empty-message && git push origin master ; true
